In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing 

In [2]:
california_house=fetch_california_housing()

In [3]:
california_house 


{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [4]:
california_house.feature_names 

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [5]:
df=pd.DataFrame(california_house.data,columns=california_house.feature_names)

In [6]:
df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [7]:
california_house.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [8]:
df.describe

<bound method NDFrame.describe of        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

     

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB


In [11]:
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [15]:
op=california_house.target

In [13]:
california_house.target_names

['MedHouseVal']

In [14]:
df.shape

(20640, 8)

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df,op,test_size=0.2)

In [17]:
X_test

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
13756  1.8152      17.0  4.223660   1.024030      1412.0  2.609982     34.06   
6407   7.7307      34.0  6.619529   1.074074       980.0  3.299663     34.13   
2136   3.7578      24.0  5.061538   0.957692       781.0  3.003846     36.80   
19769  2.6250      27.0  5.378788   1.080808       508.0  2.565657     39.82   
19895  1.7734      23.0  4.283784   1.058559       806.0  3.630631     36.30   
...       ...       ...       ...        ...         ...       ...       ...   
12012  6.1550      16.0  6.998316   0.986532      2036.0  3.427609     33.92   
18880  1.1835      30.0  3.350505   1.068687      1794.0  1.812121     38.10   
14788  2.3194      32.0  4.389671   1.025822      1142.0  2.680751     32.58   
16711  3.5682      10.0  6.100875   1.023907      4660.0  2.717201     35.03   
1842   5.5357      40.0  6.150442   0.970501       796.0  2.348083     37.91   

       Longitude  
13756    -117.16  
6407     -118.02  
2136     -119.73  
19769    -122.11  
19895    -119.21  
...          ...  
12012    -117.58  
18880    -122.26  
14788    -117.13  
16711    -120.50  
1842     -122.29  

[4128 rows x 8 columns]

In [18]:
X_train

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
5081   3.0455      48.0  5.230366   1.073298      1176.0  3.078534     33.98   
1603   6.2275      34.0  6.215302   0.975089      2865.0  2.548932     37.88   
5830   5.0865      36.0  6.086331   0.946043       778.0  2.798561     34.20   
6687   3.3750      42.0  5.095541   1.090764      1668.0  2.656051     34.14   
18857  1.5923      52.0  5.537423   1.208589      1926.0  2.363190     41.20   
...       ...       ...       ...        ...         ...       ...       ...   
10665  7.7900      25.0  6.514368   1.031609       866.0  2.488506     33.61   
15543  8.5957       8.0  8.105882   1.008824      1045.0  3.073529     33.07   
11737  2.6701      41.0  4.888732   1.060563      1680.0  2.366197     38.89   
11843  2.9559      15.0  5.272152   1.110759       816.0  2.582278     39.96   
16152  3.8899      52.0  4.500000   1.047535      1202.0  2.116197     37.77   

       Longitude  
5081     -118.30  
1603     -122.14  
5830     -118.31  
6687     -118.07  
18857    -122.27  
...          ...  
10665    -117.87  
15543    -117.07  
11737    -121.08  
11843    -120.93  
16152    -122.48  

[16512 rows x 8 columns]

In [20]:
len(y_train)

16512

In [22]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
x_data=scaler.fit_transform(X_train)

In [23]:
x_data

array([[-4.28403713e-01,  1.53762397e+00, -8.01111208e-02, ...,
        -1.71625176e-03, -7.74515371e-01,  6.35644044e-01],
       [ 1.24585064e+00,  4.25645561e-01,  3.39056611e-01, ...,
        -4.73863139e-02,  1.05320625e+00, -1.28729364e+00],
       [ 6.45497337e-01,  5.84499619e-01,  2.84169070e-01, ...,
        -2.58596412e-02, -6.71413126e-01,  6.30636394e-01],
       ...,
       [-6.25925739e-01,  9.81634763e-01, -2.25503298e-01, ...,
        -6.31444371e-02,  1.52653928e+00, -7.56482720e-01],
       [-4.75548022e-01, -1.08346799e+00, -6.23281439e-02, ...,
        -4.45107218e-02,  2.02799111e+00, -6.81367967e-01],
       [ 1.58893036e-02,  1.85533208e+00, -3.90939505e-01, ...,
        -8.47031229e-02,  1.00165513e+00, -1.45755375e+00]])

In [24]:
from sklearn.ensemble import RandomForestRegressor

In [49]:
model=RandomForestRegressor(n_estimators=80,random_state=10)
model.fit(X_train,y_train)

RandomForestRegressor(n_estimators=80, random_state=10)

In [39]:
y_pred = model.predict(X_test)

In [34]:
y_pred

array([1.0072   , 4.3472035, 0.90935  , ..., 1.37242  , 1.82881  ,
       3.3527604])

In [35]:
from sklearn.metrics import accuracy_score

In [50]:
model.score(X_test,y_test)

0.7949388076874029

# Random Classifier

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
df=pd.read_csv('cardekho_data.csv')

In [4]:
df

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Seller_Type Transmission  Owner  
0        Dealer       Manual      0  
1        Dealer       Manual      0  
2        Dealer       Manual      0  
3        Dealer       Manual      0  
4        Dealer       Manual      0  
..          ...          ...    ...  
296      Dealer       Manual      0  
297      Dealer       Manual      0  
298      Dealer       Manual      0  
299      Dealer       Manual      0  
300      Dealer       Manual      0  

[301 rows x 9 columns]

In [6]:
df.Fuel_Type.unique()

array(['Petrol', 'Diesel', 'CNG'], dtype=object)

In [7]:
df.Seller_Type.unique()

array(['Dealer', 'Individual'], dtype=object)

In [8]:
df.Transmission.unique()

array(['Manual', 'Automatic'], dtype=object)

In [9]:
df.Owner.unique()

array([0, 1, 3])

In [12]:
for_train=df.drop(['Car_Name'],axis=1)

In [13]:
for_train

Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0    2014           3.35           5.59       27000    Petrol      Dealer   
1    2013           4.75           9.54       43000    Diesel      Dealer   
2    2017           7.25           9.85        6900    Petrol      Dealer   
3    2011           2.85           4.15        5200    Petrol      Dealer   
4    2014           4.60           6.87       42450    Diesel      Dealer   
..    ...            ...            ...         ...       ...         ...   
296  2016           9.50          11.60       33988    Diesel      Dealer   
297  2015           4.00           5.90       60000    Petrol      Dealer   
298  2009           3.35          11.00       87934    Petrol      Dealer   
299  2017          11.50          12.50        9000    Diesel      Dealer   
300  2016           5.30           5.90        5464    Petrol      Dealer   

    Transmission  Owner  
0         Manual      0  
1         Manual      0  
2         Manual      0  
3         Manual      0  
4         Manual      0  
..           ...    ...  
296       Manual      0  
297       Manual      0  
298       Manual      0  
299       Manual      0  
300       Manual      0  

[301 rows x 8 columns]

In [14]:
from sklearn.preprocessing import LabelEncoder

In [16]:
encoder=LabelEncoder()
df['enc_transmission']=encoder.fit_transform(df['Transmission'])

In [17]:
df.enc_transmission

0      1
1      1
2      1
3      1
4      1
      ..
296    1
297    1
298    1
299    1
300    1
Name: enc_transmission, Length: 301, dtype: int64

In [18]:
df

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Seller_Type Transmission  Owner  enc_transmission  
0        Dealer       Manual      0                 1  
1        Dealer       Manual      0                 1  
2        Dealer       Manual      0                 1  
3        Dealer       Manual      0                 1  
4        Dealer       Manual      0                 1  
..          ...          ...    ...               ...  
296      Dealer       Manual      0                 1  
297      Dealer       Manual      0                 1  
298      Dealer       Manual      0                 1  
299      Dealer       Manual      0                 1  
300      Dealer       Manual      0                 1  

[301 rows x 10 columns]

In [19]:
df['enc_Fuel_Type']=encoder.fit_transform(df['Fuel_Type'])
df['enc_Seller_Type']=encoder.fit_transform(df['Seller_Type'])


In [20]:
df

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Seller_Type Transmission  Owner  enc_transmission  enc_Fuel_Type  \
0        Dealer       Manual      0                 1              2   
1        Dealer       Manual      0                 1              1   
2        Dealer       Manual      0                 1              2   
3        Dealer       Manual      0                 1              2   
4        Dealer       Manual      0                 1              1   
..          ...          ...    ...               ...            ...   
296      Dealer       Manual      0                 1              1   
297      Dealer       Manual      0                 1              2   
298      Dealer       Manual      0                 1              2   
299      Dealer       Manual      0                 1              1   
300      Dealer       Manual      0                 1              2   

     enc_Seller_Type  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
..               ...  
296                0  
297                0  
298                0  
299                0  
300                0  

[301 rows x 12 columns]

In [22]:
for_train=df.drop(['Car_Name','Fuel_Type','Seller_Type','Transmission','Owner'],axis=1)
y=np.array(df['Owner'])

In [23]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [24]:
for_train


Year  Selling_Price  Present_Price  Kms_Driven  enc_transmission  \
0    2014           3.35           5.59       27000                 1   
1    2013           4.75           9.54       43000                 1   
2    2017           7.25           9.85        6900                 1   
3    2011           2.85           4.15        5200                 1   
4    2014           4.60           6.87       42450                 1   
..    ...            ...            ...         ...               ...   
296  2016           9.50          11.60       33988                 1   
297  2015           4.00           5.90       60000                 1   
298  2009           3.35          11.00       87934                 1   
299  2017          11.50          12.50        9000                 1   
300  2016           5.30           5.90        5464                 1   

     enc_Fuel_Type  enc_Seller_Type  
0                2                0  
1                1                0  
2                2                0  
3                2                0  
4                1                0  
..             ...              ...  
296              1                0  
297              2                0  
298              2                0  
299              1                0  
300              2                0  

[301 rows x 7 columns]

In [25]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(for_train,y,test_size=0.2)

In [26]:
X_train

Year  Selling_Price  Present_Price  Kms_Driven  enc_transmission  \
256  2016          10.25          13.60       49562                 1   
300  2016           5.30           5.90        5464                 1   
35   2011           2.95           7.74       49998                 1   
31   2011           2.35           4.89       54200                 1   
140  2013           0.60           1.20       32000                 1   
..    ...            ...            ...         ...               ...   
264  2015           4.00           7.00       40026                 1   
238  2013           4.80           9.40       60241                 1   
247  2015           5.95           9.40       36000                 1   
204  2015           2.75           4.43       28282                 1   
36   2015           4.65           7.20       48767                 1   

     enc_Fuel_Type  enc_Seller_Type  
256              2                0  
300              2                0  
35               0                0  
31               2                0  
140              2                1  
..             ...              ...  
264              2                0  
238              2                0  
247              2                0  
204              2                0  
36               2                0  

[240 rows x 7 columns]

In [27]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=20,random_state=30)
model.fit(X_train,y_train)

RandomForestClassifier(n_estimators=20, random_state=30)

In [28]:
model.score(X_test,y_test)

0.9180327868852459